title: Gardening Thoughts

description: >
  Ideas on how to garden in the Low Country Coastal South Carolina

author:
  name: Garden Maven
  email: gardenmaven19@gmail.com

nav_pages:
  - about.md
  - contact.md

max-width: 800px

show_excerpts: true
show_rss_feed: true
show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

content_selector: div.post-content,div.home
